Eng 905
rhythmictech/terraform-aws-alb-ecs-task pull request #1
Opened 2020-06-08 16:51 UTC by sblack4

2020-06-08 21:43 UTC, sblack4 commented
I got the Fargate example working!!!

2020-06-10 16:38 UTC, cdaniluk requested changes

2020-06-10 16:38 UTC, cdaniluk commented on README.md
> +  source = "github.com/rhythmictech/terraform-aws-alb-ecs-task?ref=master"
```suggestion
  source = "rhythmictech/aws/alb-ecs-task"
```
I think, anyway?

2020-06-10 16:38 UTC, cdaniluk commented on iam.tf
> +  name_prefix = "${var.name}-ecs-task-policy-${count.index}"
```suggestion
  name_prefix = "${var.name}-ecs-task-policy-${count.index}-"
```
I'm not even sure we need `name_prefix` at all for this particular resource type but don't feel strongly

2020-06-10 16:38 UTC, cdaniluk commented on iam.tf
> +      "ssm:GetParameters",
is this needed?

2020-06-10 16:38 UTC, cdaniluk commented on iam.tf
> +      "ecr:GetAuthorizationToken",
I don't think we should grant blanket ECR access by default, the user of the module should determine what ECR access to provide

2020-06-10 16:38 UTC, cdaniluk commented on locals.tf
> +  lb_target_group_name_prefix = "${substr(var.name, 0, 2)}-tg-"
```suggestion
  lb_target_group_name_prefix = "${substr(var.name, 0, 5)}-"
```
Just a thought that maybe we don't need to say tg when it's a tg.. and pick up some extra letters for better context?

2020-06-10 16:38 UTC, cdaniluk commented on locals.tf
> +      "awslogs-region" : "${var.region}",
compute region with a data source

2020-06-10 16:38 UTC, cdaniluk commented on main.tf
> +  vpc_id      = var.vpc_id
sort

2020-06-10 16:38 UTC, cdaniluk commented on main.tf
> +  from_port                = var.container_port
sort

2020-06-10 16:38 UTC, cdaniluk commented on main.tf
> +  protocol    = "HTTP"
should this be a var? (not sure)

2020-06-10 16:38 UTC, cdaniluk commented on main.tf
> +  protocol          = "HTTP" #tfsec:ignore:AWS004
same as above?

2020-06-10 16:38 UTC, cdaniluk commented on main.tf
> +module "container_definition" {
I don't think we need to use their container definition, I think my blank json file was sufficient. I Don't see an advantage to asking the user of this module to specify env vars, port mappings and secrets to this module when they'll be steamrolled by the actual deployment.

2020-06-10 16:38 UTC, cdaniluk commented on main.tf
> +    assign_public_ip = (var.launch_type == "FARGATE")
might we still want a public IP when using ec2 in some use cases?

2020-06-10 16:38 UTC, cdaniluk commented on variables.tf
> +variable "environment_variables" {
don't think we need this since it's a dummy task

2020-06-10 16:38 UTC, cdaniluk commented on variables.tf
> +variable "secrets" {
don't think we need this since it's a dummy task

2020-06-10 16:38 UTC, cdaniluk commented on variables.tf
> +variable "region" {
compute this

2020-06-10 16:38 UTC, cdaniluk commented on variables.tf
> +variable "container_image" {
don't think we need this since it's a dummy task

2020-06-10 16:38 UTC, cdaniluk commented on variables.tf
> +variable "additional_ecs_task_policy_arns" {
❤️

2020-06-10 16:38 UTC, cdaniluk commented on locals.tf
> +  log_configuration = {
don't think we need this since it's a dummy task.. which then eliminates the need for region at all too I think?

2020-06-10 16:38 UTC, cdaniluk commented on locals.tf
> +  port_mappings = [
don't think we need this since it's a dummy task

2020-06-10 16:57 UTC, sblack4 commented on iam.tf
> +      "ssm:GetParameters",
Nah, this was yanked from OF IAM roles

2020-06-10 16:57 UTC, sblack4 commented on iam.tf
> +      "ecr:GetAuthorizationToken",
I guess icksnay on everything but the logging which is necessary for the logging?

2020-06-10 16:58 UTC, sblack4 commented on locals.tf
> +  log_configuration = {
I like the idea of being able to use this for more than just dummy tasks. Maybe someday we could even use a descendent of this module for deployments

2020-06-10 17:03 UTC, sblack4 commented on locals.tf
> +  port_mappings = [
but I already wrote it 😿

2020-06-10 17:03 UTC, sblack4 commented on main.tf
> +  protocol    = "HTTP"
it could be, I guess encrypting private traffic is a good idea

2020-06-10 17:03 UTC, sblack4 commented on main.tf
> +module "container_definition" {
This is the pattern with one of our clients but will that be our general pattern?

2020-06-10 17:03 UTC, sblack4 commented on variables.tf
> +variable "container_image" {
We can make it only do dummy tasks or just provide defaults so the user of the module has the choice between dummy or real task

2020-06-10 17:05 UTC, smiller171 commented on README.md
> +  source = "github.com/rhythmictech/terraform-aws-alb-ecs-task?ref=master"
This one isn't in the registry yet, so that won't work. 

Should ref a tag though, not a branch.

2020-06-10 17:36 UTC, smiller171 requested changes

2020-06-10 17:36 UTC, smiller171 commented on examples/ec2/README.md
> +| aws | n/a |
need a version

2020-06-10 17:36 UTC, smiller171 commented on examples/ec2/main.tf
> +variable "vpc_id" {}
even in an example, vars that aren't fully defined and aren't in a `variables.tf` bug me

2020-06-10 17:36 UTC, smiller171 commented on examples/fargate/README.md
> +| aws | n/a |
need a version

2020-06-10 17:36 UTC, smiller171 commented on examples/fargate/README.md
> +| vpc\_id | ####################################### Tags and Naming ####################################### | `any` | n/a | yes |
something is wrong here

2020-06-10 17:36 UTC, smiller171 commented on examples/fargate/main.tf
> +}
Your examples are all totally overkill. You don't need this in an example

2020-06-10 17:36 UTC, smiller171 commented on iam.tf
> +resource "aws_iam_role_policy" "additional" {
If you're attaching policy ARNs, this should be a `policy_attachment`, not a `policy`

2020-06-10 17:36 UTC, smiller171 commented on iam.tf
> +      "ecr:GetAuthorizationToken",
stop defining this policy manually at all. Use the aws-maintained ecs-exec policy IMO

2020-06-10 17:36 UTC, smiller171 commented on locals.tf
> +  ecs_task_iam_role_name_prefix = "${substr(var.name, 0, 22)}-ecs-task-"
Our convention is to _not_ include the type of resource in the name, so pull out the `-ecs-task` and just use `module.tags.name32`

2020-06-10 17:36 UTC, smiller171 commented on locals.tf
> +  log_configuration = {
Yeah, the module should be able to support both, unless you want a separate module explicitly for dummy tasks

2020-06-10 17:36 UTC, smiller171 commented on locals.tf
> +  port_mappings = [
This module doesn't seem to be specifically for dummy tasks

2020-06-10 17:36 UTC, smiller171 commented on main.tf
> +  protocol    = "HTTP"
yeah, definitely should be a var

2020-06-10 17:36 UTC, smiller171 commented on main.tf
> +module "container_definition" {
I think we should either have a separate module for creating dummy tasks (the name of this one doesn't indicate it's a dummy) or have a flag in this one that causes it to passy a dummy task.

2020-06-10 17:36 UTC, smiller171 commented on main.tf
> +  family                   = "${var.name}-task-def"
I'm fairly sure our convention is to _not_ include the resource type in the name

2020-06-10 17:36 UTC, smiller171 commented on main.tf
> +  name            = "${var.name}-service"
no type in name

2020-06-10 17:36 UTC, smiller171 commented on main.tf
> +    # ignore_changes = [task_definition]
This shouldn't be commented out so it needs changing, it should use a flag of some kind.

2020-06-10 17:36 UTC, smiller171 commented on main.tf
> +    assign_public_ip = (var.launch_type == "FARGATE")
@sblack4's conclusion here is wrong anyway. You don't need a public IP when using fargate. You only need a public IP if _in a public subnet_

2020-06-10 17:36 UTC, smiller171 commented on outputs.tf
>  }
Don't output the entire object. Output the necessary values

2020-06-10 17:36 UTC, smiller171 commented
Of course you marked draft _while I was reviewing_

oh well

2020-06-10 18:00 UTC, cdaniluk commented on README.md
> +  source = "github.com/rhythmictech/terraform-aws-alb-ecs-task?ref=master"
shouldn't it be fully qualified if using it that way?

2020-06-10 18:01 UTC, cdaniluk commented on iam.tf
> +      "ecr:GetAuthorizationToken",
If they have a base execution role, yeah.. people who didn't use the AWS provided roles for other things had sadness as AWS released new features. I think those roles are pretty safe because they only grant access to the lowest level fundamentals like SSM, CloudWatch, etc

2020-06-10 18:02 UTC, cdaniluk commented on variables.tf
> +variable "container_image" {
but the readme says dummy task :)

you make a reasonable point though, and I can support your thinking. But if we do it that way, make the readme indicate how to use it in a dummy mode vs real mode

2020-06-10 18:02 UTC, cdaniluk commented on locals.tf
> +  log_configuration = {
per note above, I am good with this as long as the README is clear on both use cases

2020-06-10 18:05 UTC, cdaniluk commented on examples/ec2/main.tf
> +variable "vpc_id" {}
I don't feel strongly about this.. I mostly don't want to create friction around creating these examples.

2020-06-10 18:49 UTC, sblack4 commented on variables.tf
> +variable "container_image" {
🥳

2020-06-10 18:53 UTC, sblack4 commented on examples/fargate/main.tf
> +}
I do it all for the provisions 
![image](https://user-images.githubusercontent.com/15880760/84306880-1820cb80-ab2a-11ea-84fa-46e5e866dbbf.png)

2020-06-10 18:56 UTC, cdaniluk requested changes

2020-06-10 18:56 UTC, cdaniluk commented on README.md
> +Creates an ECS service, a dummy task, ALB target group, ALB listener, and CloudWatch logging.
fixme

2020-06-10 19:47 UTC, sblack4 commented on iam.tf
> +      "ecr:GetAuthorizationToken",
this one? https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ecr:GetAuthorizationToken",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        "ecr:BatchGetImage",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "*"
    }
  ]
}
```
🤷

2020-06-10 19:55 UTC, sblack4 commented on outputs.tf
>  }
this requires thinking and decisions to be made in advance

2020-06-10 19:56 UTC, sblack4 commented on outputs.tf
>  }
Outputting the entire object gives the most flexibility for future developers and fewer random PRs when the thing we want isn't in the outputs

2020-06-10 19:56 UTC, sblack4 commented on outputs.tf
>  }
I really don't care if we have any outputs at all

2020-06-10 20:51 UTC, cdaniluk commented on outputs.tf
>  }
I don't think we should output absolutely everything under the sun in every module we make, because it can lead to excessive coupling. Being promiscuous always seems like the best long-term play but ultimately results in STDs.

Ultimately though I think emiting the task definition in this case makes sense.

2020-06-10 20:55 UTC, cdaniluk approved these changes

2020-06-10 20:55 UTC, cdaniluk commented on iam.tf
> +resource "aws_iam_role_policy" "additional" {
Uggh yea this doesn't work, this will redefine the role's inline policy n times. Good catch.

2020-06-10 20:55 UTC, cdaniluk commented on main.tf
> +    # Subsequent deploys are done via code pipeline
```suggestion
    # Subsequent deploys are likely to be done through an external deployment pipeline
```
(might not be code pipeline)

2020-06-10 21:02 UTC, sblack4 commented on locals.tf
> +  ecs_task_iam_role_name_prefix = "${substr(var.name, 0, 22)}-ecs-task-"
We decided not to use the tag modules in modules but I can replicate the functionality

2020-06-11 16:06 UTC, cdaniluk commented on iam.tf
> +      "ecr:GetAuthorizationToken",
ffs, that role sucks. I guess use it though. I'm not wild about unfettered ECR access, but we aren't organized enough yet to manage our own base roles methinks

2020-06-11 16:06 UTC, cdaniluk approved these changes

2020-06-11 16:13 UTC, merged